// src/app/patients/patient-summary/patient-summary.component.ts
import { JsonPipe } from "@angular/common";
import { Component, Input } from "@angular/core";
import Patient from "../business/patient";
import { FilePanelComponent } from "../file-panel/file-panel.component";
import PatientsService from "../patients.service";

@Component({
  selector: "app-patient-summary",
  standalone: true,
  imports: [JsonPipe, FilePanelComponent],
  templateUrl: "./patient-summary.component.html",
  styleUrl: "./patient-summary.component.css"
})
export class PatientSummaryComponent {
  #id: string = "";
  patient?: Patient;

  constructor(private patientsService: PatientsService) {}

  @Input()
  set id(id: string) {
    this.#id = id;
    this.getFolder();
  }

  get id() {
    return this.#id;
  }

  getFolder(): void {
    this.patientsService.load(this.id).subscribe((val: Patient) => {
      this.patient = val;
    });
  }
}

@if (!patient) {
  <div>Loading</div>
} @else {
  <app-file-panel [file]="patient" opened="true">
    <ng-container headers>
      <span> {{ patient.entry_year }}-{{ patient.entry_order }} </span>
      <span className="no-mobile">{{ patient.name }}</span>
      <span className="no-mobile">{{ patient.year_of_birth }}</span>
    </ng-container>

    <!-- <TwoColumns>
    <Panel fixed label="Identification">
      <IO.Number label="Entry Year" value={file.entry_year} />
      <IO.Number label="Entry Order" value={file.entry_order} />
      <IO.String label="Name" value={file.name} />
      <IO.String label="Sex" value={file.sex} />
      <IO.Number label="Year of birth" value={file.year_of_birth} />
      <IO.String
        label="Age today"
        value={file.actualAge() as string}
        variable
      />
      <IO.String label="Pathology" value={file.pathology} />
      <IO.Text label="Comments" value={file.comments} />
    </Panel>
    <Panel fixed label="Address">
      <IO.String width={1} label="Phone" value={file.phone} />
      <IO.String label="District" value={file.address_district} />
      <IO.String label="Union" value={file.address_union} />
      <IO.String label="Upazilla" value={file.address_upazilla} />
      <IO.String label="Address Comments" value={file.address_comments} />
    </Panel>
  </TwoColumns> -->
  </app-file-panel>
}
<pre>
  {{ patient | json }}
</pre>

// src/app-folder/blocs/patient-summary.tsx
import React from "react";
import Button from "react-bootstrap/Button";

import { bridgeTo } from "../../bridge";
import Patient from "../../../legacy/app-old/v2/models/Patient";
import "../../styles/x-style-collapsible";
import "../../styles/x-style-panel";
import IONumber from "../../widget/io-number";
import IOString from "../../widget/io-string";
import IOText from "../../widget/io-text";

export default function PatientSummary({
  patient
}: {
  patient: Patient;
}): React.ReactNode {
  if (!patient) {
    return <div>No patient selected</div>;
  }
  return (
    <x-style-collabsible opened="1">
      <span slot="header" className="no-mobile">
        <img
          slot="header"
          src="/static/img/patient.gif"
          alt="Patient"
          className="inline"
        />
        Patient
      </span>
      <span slot="header">
        {patient.entry_year}-{patient.entry_order}
      </span>
      <span slot="header" className="no-mobile">
        {patient.name}
      </span>
      <span slot="header" className="no-mobile">
        {patient.year_of_birth}
      </span>
      <Button
        href={"#/folder/" + patient.getId() + "/"}
        variant="outline-info"
        style={{ width: "100%" }}
      >
        View the Patient
      </Button>
      <div className="columns">
        <x-style-panel label="Identification">
          <IONumber label="Entry Year" value={patient.entry_year} />
          <IONumber label="Entry Order" value={patient.entry_order} />
          <IOString label="Name" value={patient.name} />
          <IOString label="sex" value={patient.sex} />
          <IONumber label="Year of birth" value={patient.year_of_birth} />
          <IOString label="Age today" value={patient.actualAge() as string} />
          <IOString label="pathology" value={patient.pathology} />
          <IOText label="Comments" value={patient.comments} />
        </x-style-panel>
        <x-style-panel label="Address">
          <IOString width={1} label="Phone" value={patient.phone} />
          <IOString label="District" value={patient.address_district} />
          <IOString label="Union" value={patient.address_union} />
          <IOString label="Upazilla" value={patient.address_upazilla} />
          <IOString label="Address Comments" value={patient.address_comments} />
        </x-style-panel>
      </div>
    </x-style-collabsible>
  );
}

bridgeTo("x-react-patient-summary", PatientSummary);
