// src/app/patients/file-panel/file-panel.component.ts
import { Component, Input, OnInit } from "@angular/core";
import { technical2Human } from "../../_helpers/strings";
import { icons } from "../../generic/constants";
import { DateComponent } from "../../generic/date/date.component";
import Pojo from "../business/abstracts/pojo";

@Component({
  selector: "app-file-panel",
  standalone: true,
  templateUrl: "./file-panel.component.html",
  styleUrl: "./file-panel.component.css",
  imports: [DateComponent]
})
export class FilePanelComponent implements OnInit {
  @Input() file: Pojo = new Pojo();
  @Input() model: string = "";

  statusOpened: boolean = false;
  view: string = "undefined";

  ngOnInit(): void {
    // So easier...
    this.view = window.location.hash.substring(1);

    if (this.view == this.file.uuid) {
      this.statusOpened = true;
    }
  }

  toggleOpen() {
    this.statusOpened = !this.statusOpened;
  }

  get icon(): string {
    if (this.file) {
      return icons.models[(this.model as keyof typeof icons.models) ?? ""];
    }
    return "";
  }

  get label(): string {
    return technical2Human(this.model ?? "");
  }
}

<div attr.data-testId="{{ file.uuid }}" class="panel">
  <div (click)="toggleOpen()" attr.data-testId="{{ file.uuid }}-open">
    <label>
      <img src="{{ icon }}" alt="{{ model }}" class="inline" />
      {{ label }}
    </label>
    <ng-content select="[headers]"></ng-content>
    @if ($any(file).date) {
      <span>{{ $any(file).date }}</span>
    }
  </div>
  @if (statusOpened) {
    <div class="body" attr.data-testId="{{ file.uuid }}-content">
      <div class="technical">
        <div>{{ model }}#{{ file.id }}</div>
        <div>created at <app-date [value]="file.created_at"></app-date></div>
        <div>updated at <app-date [value]="file.updated_at"></app-date></div>
        <div>by {{ file.last_user }}</div>
      </div>
      <div class="button-group">
        <app-confirm></app-confirm>
        @if (file.isLocked()) {
          @if (authService.has("folder.unlock")) {
            <button
              class="btn btn-outline-secondary"
              attr.data-testid="{{ file.uuid }}-button-unlock"
              (click)="doUnlock()"
            >
              Unlock
            </button>
          } @else {
            <span>File is locked</span>
          }
        } @else {
          @if (editMode) {
            <button
              class="btn btn-success"
              attr.data-testid="{{ file.uuid }}-button-save"
              (click)="doSave()"
            >
              Save
            </button>
            <button
              class="btn btn-warning"
              attr.data-testid="{{ file.uuid }}-button-cancel"
              (click)="doCancel()"
            >
              Cancel
            </button>
            @if (authService.has("folder.delete") && file.canDelete()) {
              <button
                class="btn btn-danger"
                attr.data-testid="{{ file.uuid }}-button-delete"
                (click)="doDelete()"
              >
                Delete
              </button>
            }
          } @else {
            <button
              *ngIf="authService.has('folder.edit')"
              class="btn btn-outline-primary"
              attr.data-testid="{{ file.uuid }}-button-edit"
              (click)="goEdit()"
            >
              Edit
            </button>
          }
        }
      </div>
      <div data-role="body" class="body">
        <ng-content></ng-content>
      </div>
    </div>
  }
</div>

// legacy/react/app-patient/blocs/file-panel.tsx
import React, { useState } from "react";
import PatientRelated from "../../business/abstracts/patient-related";
import Pojo from "../../business/abstracts/pojo";
import Folder from "../../business/folder";
import Patient from "../../business/patient";
import { icons } from "../../config";
import { date2HumanString, normalizeDate } from "../../utils/date";
import ActionButton, { ActionStyles } from "../../widget/action-button";
import ActionConfirm from "../../widget/action-confirm";
import { EditContext } from "../../widget/io-abstract";
import { notifySuccess } from "../../widget/notification";
import Panel from "../../widget/panel";
import Restricted from "../../widget/restricted";
import { folderFileDelete, folderFileUnlock } from "../loaders";

export type FolderUpdateCallback = (folder: Folder | undefined) => void;

export default function FilePanel({
  file,
  folder,
  header,
  children,
  footer,
  closed,
  onUpdate
}: {
  file: Pojo;
  folder: Folder;
  header?: React.ReactNode;
  children: React.ReactNode;
  footer?: React.ReactNode;
  closed?: boolean;
  onUpdate: FolderUpdateCallback;
}): React.ReactNode {
  const [editState, updateEditState] = useState(false);

  const goEdit = (file: Pojo) => {
    if (location.search == "?dev") {
      updateEditState(true);
      return;
    }
    location.hash = [
      "folder",
      "" + folder.getId(),
      "file",
      file.getModel(),
      "" + file.getId(),
      "edit"
    ].join("/");
  };

  const doUnlock = () => {
    folderFileUnlock(file)
      .then((file) => folder.withFile(file))
      .then(notifySuccess("File unlocked"))
      .then((newFolder) => onUpdate(newFolder))
      .then(() => goEdit(file));
  };

  const doSave = () => {
    Promise.resolve()
      .then(notifySuccess("File saved"))
      .then((f) => {
        updateEditState(false);
        return f;
      });
  };

  const doDelete = () => {
    folderFileDelete(file)
      .then(notifySuccess("File deleted"))
      .then((folder) => onUpdate(folder));
  };

  return (
    <Panel
      dataRole={file.uid()}
      closed={closed}
      header={
        <>
          <span className="first">
            <img
              src={
                icons.models[
                  (file.getModel() as keyof typeof icons.models) ?? ""
                ]
              }
              alt={file.getTitle()}
              className="inline"
            />
            {
              // TODO: use interface?
              "date" in file ? (
                <span className="no-mobile">
                  {date2HumanString(normalizeDate(file["date"] as Date))}
                </span>
              ) : null
            }
            <span data-role="type" className="no-mobile">
              {file.getTitle()}
            </span>
          </span>
          {header}
        </>
      }
      actions={
        <>
          {file.isLocked() ? (
            // File is locked
            file instanceof PatientRelated && (
              <Restricted requiresTransaction="folder.unlock">
                <ActionConfirm
                  style={ActionStyles.Alternate}
                  buttonText="Unlock"
                  discrete={true}
                  onOk={() => doUnlock()}
                >
                  <div>
                    Are you sure you want to unlock the File {file.getModel()}
                    ?
                    <br />
                    Anybody will then be able to edit it.
                  </div>
                </ActionConfirm>
              </Restricted>
            )
          ) : // File is not locked
          editState ? (
            <>
              <ActionButton
                style={ActionStyles.Confirm}
                text="Save"
                onClick={() => doSave()}
              />
              <ActionButton
                style={ActionStyles.Cancel}
                onClick={() => updateEditState(false)}
              />
              {file instanceof PatientRelated &&
                (!(file instanceof Patient) ||
                  folder.getFilesRelatedToPatient().length == 0) && (
                  <ActionConfirm
                    style={ActionStyles.Delete}
                    buttonText="Delete"
                    discrete={true}
                    onOk={() => doDelete()}
                  >
                    <div>
                      Are you sure you want to DELETE the File {file.getModel()}
                      ?
                    </div>
                  </ActionConfirm>
                )}
            </>
          ) : (
            <ActionButton
              style={ActionStyles.Edit}
              text="Edit"
              onClick={() => goEdit(file)}
            />
          )}
        </>
      }
    >
      <div className="technical" data-testid={file.uid() + "-open"}>
        <div>
          {file.getModel()}#{file.id}
        </div>
        <div>created at {date2HumanString(normalizeDate(file.created_at))}</div>
        <div>updated at {date2HumanString(normalizeDate(file.updated_at))}</div>
        <div>by {file.last_user}</div>
      </div>
      <EditContext.Provider value={editState}>
        <form id="file">{children}</form>
      </EditContext.Provider>
      {footer}
    </Panel>
  );
}
