// src/app-folder/patient-summary.tsx
import React from "react";

import Folder from "../business/folder";
import Patient from "../business/patient";

import TwoColumns from "../widget/two-columns";
import FilePanel from "./blocs/file-panel";
import Panel from "../widget/panel";
import IO from "../widget/io";

export default function PatientSummary({
  file,
  folder
}: {
  file: Patient;
  folder: Folder;
}): React.ReactNode {
  return (
    <FilePanel
      closed
      file={file}
      folder={folder}
      headers={[
        <span>
          {file.entry_year}-{file.entry_order}
        </span>,
        <span className="no-mobile">{file.name}</span>,
        <span className="no-mobile">{file.year_of_birth}</span>
      ]}
    >
      <TwoColumns>
        <Panel fixed label="Identification">
          <IO.Number label="Entry Year" value={file.entry_year} />
          <IO.Number label="Entry Order" value={file.entry_order} />
          <IO.String label="Name" value={file.name} />
          <IO.String label="sex" value={file.sex} />
          <IO.Number label="Year of birth" value={file.year_of_birth} />
          <IO.String label="Age today" value={file.actualAge() as string} />
          <IO.String label="pathology" value={file.pathology} />
          <IO.Text label="Comments" value={file.comments} />
        </Panel>
        <Panel fixed label="Address">
          <IO.String width={1} label="Phone" value={file.phone} />
          <IO.String label="District" value={file.address_district} />
          <IO.String label="Union" value={file.address_union} />
          <IO.String label="Upazilla" value={file.address_upazilla} />
          <IO.String label="Address Comments" value={file.address_comments} />
        </Panel>
      </TwoColumns>
    </FilePanel>
  );
}

// src/app/patients/patient-summary/patient-summary.component.ts
import { JsonPipe } from "@angular/common";
import { Component, Input } from "@angular/core";
import Patient from "../business/patient";
import { FilePanelComponent } from "../file-panel/file-panel.component";
import PatientsService from "../patients.service";

@Component({
  selector: "app-patient-summary",
  standalone: true,
  imports: [JsonPipe, FilePanelComponent],
  templateUrl: "./patient-summary.component.html",
  styleUrl: "./patient-summary.component.css"
})
export class PatientSummaryComponent {
  #id: string = "";
  patient?: Patient;

  constructor(private patientsService: PatientsService) {}

  @Input()
  set id(id: string) {
    this.#id = id;
    this.getFolder();
  }

  get id() {
    return this.#id;
  }

  getFolder(): void {
    this.patientsService.load(this.id).subscribe((val: Patient) => {
      this.patient = val;
    });
  }
}

@if (!patient) {
  <div>Loading</div>
} @else {
  <app-file-panel [file]="patient" opened="true">
    <ng-container headers>
      <span> {{ patient.entry_year }}-{{ patient.entry_order }} </span>
      <span className="no-mobile">{{ patient.name }}</span>
      <span className="no-mobile">{{ patient.year_of_birth }}</span>
    </ng-container>

    <!-- <TwoColumns>
    <Panel fixed label="Identification">
      <IO.Number label="Entry Year" value={file.entry_year} />
      <IO.Number label="Entry Order" value={file.entry_order} />
      <IO.String label="Name" value={file.name} />
      <IO.String label="Sex" value={file.sex} />
      <IO.Number label="Year of birth" value={file.year_of_birth} />
      <IO.String
        label="Age today"
        value={file.actualAge() as string}
        variable
      />
      <IO.String label="Pathology" value={file.pathology} />
      <IO.Text label="Comments" value={file.comments} />
    </Panel>
    <Panel fixed label="Address">
      <IO.String width={1} label="Phone" value={file.phone} />
      <IO.String label="District" value={file.address_district} />
      <IO.String label="Union" value={file.address_union} />
      <IO.String label="Upazilla" value={file.address_upazilla} />
      <IO.String label="Address Comments" value={file.address_comments} />
    </Panel>
  </TwoColumns> -->
  </app-file-panel>
}
<pre>
  {{ patient | json }}
</pre>
